version: '3'

# To start:
# - docker-compose up
# To finish:
# - docker-compose down

services:

  db:
    image: postgres:14.4
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  model:
    build: ./model/
    ports:
      - 9950:9950
    depends_on:
      - server


  server:
    build: ./
    ports:
      - 9988:8080
    depends_on:
      - redis

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    depends_on:
      - db