version: '3'

# To start: 
# - docker-compose up
# To finish:
# - docker-compose down

services:

  db:
    image: postgres:14.4
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  model:
    build:
      dockerfile: model/Dockerfile
    command: cd /home/model && python3 server.py
    ports:
      - 9950:9950
    volumes:
      - /home/mmm/market_mentor/model:/home/model
    depends_on:
      - server
  

  server:
    build:
      dockerfile: Dockerfile
    command: cd /home/market_mentor && make build_server && make start_server
    ports:
      - 9988:8080
    volumes:
      - /home/mmm/market_mentor:/home/market_mentor
    depends_on:
      - redis


  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 9966:7000
    depends_on:
      - db