name: linters_and_tests

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    container: rbeketov/mm_server
    steps:
    - uses: actions/checkout@v2 
    - run: make build_server

  test:
    runs-on: ubuntu-latest
    container: rbeketov/mm_server
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: make test_server
