name: linters_and_tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: rbeketov/ubuntu_cpp_fix
    steps:
    - uses: actions/checkout@v2 
    - run: make build

  test:
    runs-on: ubuntu-latest
    container: rbeketov/ubuntu_cpp_fix
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: make test

  memtest:
    runs-on: ubuntu-latest
    container: rbeketov/ubuntu_cpp_fix
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: make memtest
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./server/build/report